Jprn 1565 aviso actualizacion en apps
janis-commerce/app-check-updates pull request #2
Opened 2023-08-27 21:43 UTC by WilliamSaya-lvl30

Link de Tarea:
https://janiscommerce.atlassian.net/browse/JUIP-81

Link del ticket:
https://janiscommerce.atlassian.net/browse/JPRN-1565

Contexto:
Cada vez que publicamos una nueva version en el ambiente productivo, estamos dando aviso via los canales de slack públicos de cada app comentando que es lo que se subió y dejando el link. El problema de esto, es que nuestro cliente no se entera de dicha comunicación y dependemos de X persona que le comente de las nuevas mejoras y actualización. Tambien sucede que usuarios no tengan habilitado la opción que la app se actualize automáticamente desde play store y esto genera que estén usando una app que haya quedado vieja.

Necesidad:
Darle la posibilidad al usuario de saber que hay actualizaciones disponibles y tambien que pueda hacerlo desde la app.

Analisis funcional:

Revisando un poco, la idea es usar una libreria para no meternos en los problemas de mantener Android y IOS. Ademas es necesaria dado que tiene que interactuar con los servicios de google play. Dejo una que me resulto interesante [npm: sp-react-native-in-app-updates](https://www.npmjs.com/package/sp-react-native-in-app-updates)

Crear una función que pueda ser ejecutada en cuaquiera de las apps, en esta se verificara si hay una nueva version disponible antes de lanzar el popup de actualización, debe ser ejecutada al momento de abrir la app.

Posibles parámetros a recibir : curVersion, isAndroid, isDebug

Captura de pantalla de 2023-08-17 14-59-31

Como se puede probar?:

Instalandolo localmente con yalc sigiendo esta guia: [link](https://janiscommerce.atlassian.net/wiki/spaces/JAPP/pages/2341765125/C+mo+trabajo+con+el+package+UI)

Las actualizaciones de la aplicación n están disponibles solo para las cuentas de usuario que poseen la aplicación. Por lo tanto, asegúrese de que la cuenta que está utilizando haya descargado su aplicación de Google Play al menos una vez antes de usarla para probar las actualizaciones dentro de la aplicación.

2023-08-28 21:47 UTC, dam788 approved these changes
![2023-08-28_18-40](https://github.com/janis-commerce/app-check-updates/assets/60529414/5d89932d-7ec4-4720-85ad-31140a6516d0)

2023-08-29 19:38 UTC, pablonortiz approved these changes

2023-08-30 15:21 UTC, christian97dd requested changes
Will, no cumple con los requisitos para la creación de un pr, te dejo acá la docu: https://janiscommerce.atlassian.net/wiki/spaces/FIZ/pages/2590638180/Requisitos+para+la+aceptaci+n+y+creaci+n+de+un+PR
En el como probarlo, si entro al link, me lleva al linkeo del package de ui native, y tampoco hay una explicación de como lo pruebo una vez linkeado el package

2023-08-31 13:48 UTC, christian97dd requested changes

2023-08-31 13:48 UTC, christian97dd commented on App.js
Por lo que veo, el package exporta una funcion que devuelve un booleano, el App.js, no lo necesitamos, no?

2023-08-31 13:48 UTC, christian97dd commented on src/index.ts
En este archivo podés importarte Platform de react native, tiene un método 'OS', que te devuelve que sistema operativo tiene el usuario. Con esto te podes evitar la flag de isAndroid y de esa manera no lo hacemos por fuera cuando es iOS

2023-08-31 13:48 UTC, christian97dd commented on src/index.ts
> +	isDebug = false,
para el isDebug haría algo similar también, para que el package pueda ser más inteligente, podes tomar de process.env.NODE_ENV y validar que no sea production, te dejo un ejemplo de una util que hace esto: https://github.com/janis-commerce/app-analytics/blob/main/lib/utils/index.js

2023-08-31 13:48 UTC, christian97dd commented on tsconfig.json
Ojo que no tenes instalado typescript en el repo y va a estar tomando typescript de la compu de cada uno, cuando corro los tests me sale este error a mi por tener version 5.1.6:
![image](https://github.com/janis-commerce/app-check-updates/assets/49655553/f9759e6e-5e90-4079-8468-88cc4b47013d)
Te conviene tenerlo instalado en el repo

2023-09-01 13:24 UTC, christian97dd approved these changes

2023-09-01 13:27 UTC, merged