se agrego el modulo para consultar actualizaciones desde janis
janis-commerce/app-check-updates pull request #5
Opened 2023-12-12 14:02 UTC by WilliamSaya-lvl30

### Link del ticket:
https://janiscommerce.atlassian.net/browse/APPSRN-249

### Contexto:
Para mantener las apps de los usuarios actualizadas creamos el package [npm: @janiscommerce/app-check-updates](https://www.npmjs.com/package/@janiscommerce/app-check-updates) que les notifica cada vez que hay una nueva versión disponible en la play store, lo descarga e instala, agilizando mucho el proceso antiguo. 
 
Sin embargo tenemos ciertos clientes como carrefour o walmart que por motivos de seguridad, tienen bloqueado el acceso a play stores en los dispositivos. Esto trae como consecuencia que no puedan actualizar de una manera eficiente, que el equipo de desarrollo tenga que armar apks de manera manual y enviarle al PO de cada proyecto para que después puedan enviarla al cliente.

En Janis v1 se creo lo que se conoce como [JAM](https://janiscommerce.atlassian.net/wiki/spaces/JAN/pages/424378445/App+de+Picking+con+JAM+Janis+App+Manager) acronimo de Janis app manager. Esto le permite a los clientes mediante esta app podes ver si hay versiones nuevas de las apps de janis v1 y actualizar, todo por fuera del ecosistema de Play store.

### Necesidad:
Implementar una herramienta que facilite la publicación y distribución de las nuevas versiones de las apps sin necesidad de usar play store.

Analisis funcional:

Se agregan los argumento env para consultar sobre nuevas actualizaciones en dicho ambiente y app que nos dirá en que aplicación es la que necesitamos actualizar. 

El formato de respuesta cambia, ahora devolveremos un objeto con dos key: 
hasCheckedUpdate : nos dira si se logro hacer el chequeo de nuevas versiones, tanto en play store como en janis, en la app esto nos dirá si seteamos el timestamp o no.

shouldUpdateFromJanis : nos dirá si hay una nueva versión disponible en janis, en la app nos dira si debemos mostrar el modal con el mensaje de notificación.

updateFromJanis: Sera una funcion que al ejecutar descargara el apk de la app en la ruta Downloads/{app}-apk,
el apk se guardara con el nombre {app}-{envVersion}.{version}.{buildNumbre}.apk
se utiliza el package  [npm: react-native-fs](https://www.npmjs.com/package/react-native-fs) como peerDependenci para hacer la descarga.

Debemos devolver una funcion que se encargue de descargar e instalar el apk desde janis.

```
const args = {
	buildNumber,
	isDebug,
	env,
	app,
};

const response = {
	hasCheckedUpdate: boolean,
	shouldUpdateFromJanis: boolean,
	updateFromJanis: func,
};
```

### Como se puede probar?:

Instalandolo localmente con yalc sigiendo esta guia: [link](https://janiscommerce.atlassian.net/wiki/spaces/JAPP/pages/2341765125/C+mo+trabajo+con+el+package+UI)
Sustituyendo el package a linkear por @janiscommerce/app-check-updates

Instalar la peerDependenci en caso de no tenerlas ya

npm install sp-react-native-in-app-updates@1.2.0
npm i react-native-fs

luego en la home se importa la funcion y se ejecuta en algun useefect

import appCheckUpdates from '@janiscommerce/app-check-updates';

Ejecutar de esta manera

```
const testFn = async () => {
	const {hasCheckedUpdate, shouldUpdateFromJanis, updateFromJanis} = await appCheckUpdates({
		buildNumber: BUILD_NUMBER,
		env: JANIS_ENV,
		app: 'picking',
	});

	if (hasCheckedUpdate) {
		// se chequeo exitosamente, setear timestamp
	}

	if (shouldUpdateFromJanis) {
		// mostrar custom modal consultando si se desea actualizar
	}
	if (typeof updateFromJanis === 'function') {
		// comenzar la descarga de apk mediante janis
		// setear algun loading antes y despues de ejecutarlo para saber cuando termine
		await updateFromJanis();
	}
};;
```

Las actualizaciones de la aplicación están disponibles solo para las cuentas de usuario que poseen la aplicación. Por lo tanto,
si en el emulador alguna vez descargaron la app desde la app store va a chequear siempre con la app store solamente, en cambio si nunca se descargo desde la app store va a verificar por janis, esto seria lo ideal para probar este desarrollo.

Una vez que tengamos una respuesta positiva de updateFromJanis (responde true cuando sale todo ok y false si falla algo), podemos ingresar a la carpeta de descargas del telefono y ver el apk.

![Captura de pantalla de 2023-12-12 10-39-44](https://github.com/janis-commerce/app-check-updates/assets/69169114/2ed18fd0-3b3a-4cb4-93d7-6fdba5e9cf83)

2023-12-12 16:18 UTC, Maukr requested changes
- Falta agregarle el jsDoc a `checkNeedsUpdateInJanis` y `updateFromJanis` para entender que hacen con más facilidad.

- En `customVersionComparator` podes hacer que reciba dos numbers en vez de dos strings y retornar en una linea:
return newAppV - appVersion;
Si es mayor a 0 hay que actualizar

- Esto nose que opinan pero veo que se están usando todo el tiempo los typeof para validar los strings, en caso de que no debamos usar el package de app-helpers podríamos traer la util que necesitemos a este package para directamente usar el isString()

- Revisar y definir caso de la notificación de progreso con el equipo

2023-12-12 21:07 UTC, WilliamSaya-lvl30 commented
> * En `customVersionComparator` podes hacer que reciba dos numbers en vez de dos strings y retornar en una linea:
>   return newAppV - appVersion;
>   Si es mayor a 0 hay que actualizar

Esta función se debe mantener así ya que se usa en el package de sp-react-native-in-app-updates y espera este tipo de respuesta.

2023-12-13 18:30 UTC, pablodamianberdun commented on src/modules/updateFromJanis/index.ts
> +			const envVersion = env === 'janisdev' ? '-beta' : env === 'janisqa' ? '-qa' : '';
@WilliamSaya-lvl30 
Estos condicionales ternarios anidados no quedaron bien
Podes armarte un objeto y accedes al valor a traves de la key, en este caso env

Ejemplo

const envUrl = {
    janisdev: '-beta',
    janisqa: '-qa',
    janis: ''
}

const envVersion = envUrl[env]

Con esto se va a entender mejor

2023-12-13 19:14 UTC, WilliamSaya-lvl30 commented on src/modules/updateFromJanis/index.ts
> +			const envVersion = env === 'janisdev' ? '-beta' : env === 'janisqa' ? '-qa' : '';
Se hizo el ajuste

2023-12-13 19:36 UTC, pablodamianberdun commented on src/modules/updateFromJanis/index.ts
> +				!env ||
@WilliamSaya-lvl30 
tenemos que validar que env sea uno de los valores que esperamos

!['janisdev', 'janisqa', 'janis'].includes(env)

porque si no, abajo cuando quieras acceder a envVersion[env] y env no sea ninguna de esas tres opciones, va a romper

2023-12-13 20:16 UTC, WilliamSaya-lvl30 commented on src/modules/updateFromJanis/index.ts
> +				!env ||
@pablodamianberdun no lo veo necesario, en caso que se agregue ya sea un ambiente o una app no valida la api de janis de consulta en checkNeedsUpdateInJanis va a romper y devolvera el defaultResponse.

2023-12-13 20:50 UTC, Maukr approved these changes

2023-12-13 21:03 UTC, pablodamianberdun approved these changes

2023-12-13 21:05 UTC, merged